# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gxX60U6PIZnzBjrx8wbroLnOIgpDtWE
"""

pip install streamlit openai

import streamlit as st
from openai import OpenAI

# --- CONFIGURATION ---
SCHOOL_PASSWORD = "science_class_rocks" # Change this!
SYSTEM_PROMPT = """
You are a helpful teaching assistant for Year 9 Science.
Answer questions simply and encourage students to think.
Do not do their homework for them.
If asked to write an essay, refuse politely and offer an outline instead.
"""

st.set_page_config(page_title="School AI Tutor", page_icon="🎓")

# --- PASSWORD PROTECTION ---
# This stops random internet users from draining your credits
if "authenticated" not in st.session_state:
    st.session_state.authenticated = False

if not st.session_state.authenticated:
    password = st.text_input("Enter Class Password:", type="password")
    if st.button("Login"):
        if password == SCHOOL_PASSWORD:
            st.session_state.authenticated = True
            st.rerun()
        else:
            st.error("Incorrect password.")
    st.stop() # Stop the app here if not logged in

# --- MAIN APP ---
st.title("🧬 Year 9 Science Tutor AI")

# Initialize the OpenAI client using Streamlit secrets
client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "system", "content": SYSTEM_PROMPT}
    ]

# Display chat messages from history on app rerun
for message in st.session_state.messages:
    if message["role"] != "system": # Don't show the hidden system instruction
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

# React to user input
if prompt := st.chat_input("Ask a science question..."):

    # 1. Display user message
    with st.chat_message("user"):
        st.markdown(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})

    # 2. Generate response
    with st.chat_message("assistant"):
        stream = client.chat.completions.create(
            model="gpt-3.5-turbo", # Cost-effective model
            messages=[
                {"role": m["role"], "content": m["content"]}
                for m in st.session_state.messages
            ],
            stream=True,
        )
        response = st.write_stream(stream)

    # 3. Save assistant response to history
    st.session_state.messages.append({"role": "assistant", "content": response})